DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS model;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE model (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  model_name TEXT NOT NULL,
  description TEXT NOT NULL,
  git_url TEXT UNIQUE NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

